// Add new prompts here — one Question per entry. Each `prompt` should read as
// a fill-in-the-blank sentence ending in "___", with `answer` holding the true
// (often surprising) completion. Keep answers short — a word, number, or
// phrase — so bluffs are easy to write and easy to compare at reveal.

import { Question } from './types';

export const QUESTIONS: Question[] = [
  { prompt: 'A group of crows is called a ___.', answer: 'murder' },
  { prompt: 'A group of owls is called a ___.', answer: 'parliament' },
  { prompt: 'A group of raccoons is called a ___.', answer: 'gaze' },
  { prompt: 'A group of ferrets is called a ___.', answer: 'business' },
  { prompt: 'A group of porcupines is called a ___.', answer: 'prickle' },
  { prompt: 'A group of flamingos is called a ___.', answer: 'flamboyance' },
  { prompt: 'A group of jellyfish is called a ___.', answer: 'smack' },
  { prompt: "A single strand of a spider's web, ounce for ounce, is stronger than ___.", answer: 'steel' },
  { prompt: 'The world record for the largest s\'more ever made weighed ___.', answer: '1,600 pounds' },
  { prompt: 'The tallest recorded tent-pole pine tree ever measured was ___ tall.', answer: '380 feet' },
  { prompt: "The world's longest continuous hiking trail, the Great Trail in Canada, stretches ___.", answer: '15,000 miles' },
  { prompt: 'A single lightning bolt is roughly ___ hotter than the surface of the sun.', answer: '5 times' },
  { prompt: 'Honey found in ancient Egyptian tombs was still ___ after 3,000 years.', answer: 'edible' },
  { prompt: 'A bolt of static electricity from a wool blanket can reach up to ___ volts.', answer: '20,000' },
  { prompt: "The Roman Empire's official currency was, for a time, backed partly by ___.", answer: 'salt' },
  { prompt: "The average person's stomach acid is strong enough to dissolve ___.", answer: 'a razor blade' },
  { prompt: 'Octopuses have ___ hearts.', answer: 'three' },
  { prompt: 'A shrimp\'s heart is located in its ___.', answer: 'head' },
  { prompt: 'A bolt of lightning strikes the Earth about ___ times every second.', answer: '44 (times)' },
  { prompt: 'Bananas are naturally slightly ___.', answer: 'radioactive' },
  { prompt: "It's illegal in Switzerland to own just ___ guinea pig.", answer: 'one' },
  { prompt: 'The Eiffel Tower grows about ___ taller in summer heat.', answer: '6 inches' },
  { prompt: 'A "jiffy" is an actual unit of time equal to ___.', answer: '1/100th of a second' },
  { prompt: 'The Great Wall of China is not actually visible from ___.', answer: 'space with the naked eye' },
  { prompt: 'The inventor of the frisbee was, after his death, turned into ___.', answer: 'frisbees' },
  { prompt: "Wombat droppings are naturally shaped like ___.", answer: 'cubes' },
  { prompt: 'A "murder hornet" queen can live for up to ___.', answer: 'a year' },
  { prompt: "The world's oldest campground reservation system dates back to ___.", answer: '1916' },
  { prompt: 'The average tent pitched at a music festival gets left behind about ___ of the time.', answer: '1 in 20' },
  { prompt: 'The world record for longest marshmallow toss and catch is ___.', answer: '32 feet' },
  { prompt: 'A single beaver dam can back up water across an area the size of ___.', answer: 'several football fields' },
  { prompt: 'Mosquitoes are attracted more to people who have recently eaten ___.', answer: 'bananas' },
  { prompt: 'The loudest a human scream has ever officially been recorded at is ___ decibels.', answer: '129' },
  { prompt: 'The Boy Scouts of America was founded in ___.', answer: '1910' },
  { prompt: "A firefly's light is, pound for pound, the most efficient light source on Earth — it wastes almost no ___.", answer: 'heat' },
  { prompt: 'Squirrels plant thousands of trees each year by ___.', answer: 'forgetting where they buried acorns' },
  { prompt: "It's a myth that you lose most of your body heat through your head — you actually lose it fastest through ___.", answer: 'whichever part is exposed' },
  { prompt: 'A tick can survive underwater for up to ___.', answer: '3 days' },
  { prompt: 'The world\'s largest campfire (by volume of wood) used over ___ of timber.', answer: '400 tons' },
  { prompt: 'A "brinicle" is a real natural phenomenon: an icicle that forms ___.', answer: 'underwater' },
  { prompt: 'Sharks existed before ___.', answer: 'trees' },
  { prompt: 'The Twinkie was originally invented with a ___ filling.', answer: 'banana' },
  { prompt: "Cows have best friends and get measurably stressed when ___.", answer: 'separated from them' },
  { prompt: "The dot over a lowercase 'i' or 'j' has a name: it's called a ___.", answer: 'tittle' },
  { prompt: "The world's tallest sandcastle ever built stood ___.", answer: 'over 57 feet' },
  { prompt: 'Astronauts can\'t ___ in space.', answer: 'burp' },
  { prompt: "A crocodile can't stick its tongue out because ___.", answer: 'it\'s attached to the roof of its mouth' },
  { prompt: 'The Hawaiian pizza was actually invented in ___.', answer: 'Canada' },
  { prompt: 'A single cloud can weigh over ___.', answer: '1 million pounds' },
  { prompt: 'The word "camp" comes from the Latin "campus," originally meaning ___.', answer: 'open field' },
  { prompt: "There's a national park where it can legally ___ inside a campground.", answer: 'snow in July (Denali)' },
  { prompt: 'Moose can dive underwater to depths of ___ to eat plants.', answer: '18 feet' },
  { prompt: 'A "campfire" story that predates written language: cave paintings suggest humans have been telling stories around fire for at least ___.', answer: '40,000 years' },
  { prompt: 'The tallest recorded human-built bonfire required a burn permit that took ___ to approve.', answer: 'months' },
  { prompt: 'A single tree can release enough oxygen in a year to support ___ people breathing.', answer: 'two' },
  { prompt: "It's possible to hear a wolf's howl from up to ___ away on a still night.", answer: '6 miles' },
  { prompt: 'The world\'s largest rubber duck ever floated was ___ tall.', answer: '61 feet' },
  { prompt: "A hummingbird's heart beats up to ___ times per minute.", answer: '1,260' },
  { prompt: 'The first s\'more recipe was published in a Girl Scout guidebook in ___.', answer: '1927' },
  { prompt: 'Standing under a tree in a thunderstorm is dangerous mainly because ___.', answer: 'the tree is often the tallest lightning target nearby' },
];
